#!/bin/bash
# Lesson 2

# Test cleaning
# touch -a -m -t 201512180130.09 ~/RECYCLE/old_test_file

usage() { echo "Usage: smr [-r] file|folder"; exit 1; }

echo 'Safe remove v.0.1'

while getopts ":r" opt; do
    case ${opt} in
        r )  IS_R=1
             ;;
        \? ) usage
             ;;
    esac
done

unset FILENAME
shift $((OPTIND-1))
FILENAME=$@

if [ -z "$FILENAME" ];  then
    usage
fi

if [[ -d $FILENAME ]] || [[ -f $FILENAME ]]; then
    if [[ "$IS_R" -eq 1 ]] && [[ -f $FILENAME ]]; then
         usage
    fi
else
    usage
fi

mkdir -p ~/RECYCLE
find ~/RECYCLE* -mtime +7 -exec rm {} \;

now=$(date +"%m_%d_%Y_%I-%M-%S")

echo $now
echo $FILENAME

find -wholename $FILENAME | tar -cvf ~/RECYCLE/backup_$now.tar -T -
